version: "3.8"

services:
  trades-receiver-service:
    container_name: trades-receiver-service
    image: trades-receiver-service
    build:
      dockerfile: Dockerfile
      context: .
      args:
        SERVICE_NAME: trades-receiver-service
    env_file: trades-receiver-service/.env
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:50051:50051"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - insider-trades

  telegram-notification-service:
    container_name: telegram-notification-service
    image: telegram-notification-service
    build:
      dockerfile: Dockerfile
      context: .
      args:
        SERVICE_NAME: telegram-notification-service
    env_file: telegram-notification-service/.env
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - rabbitmq
      - trades-receiver-service
    networks:
      - insider-trades

  api-gateway-service:
    container_name: api-gateway-service
    image: api-gateway-service
    build:
      dockerfile: Dockerfile
      context: .
      args:
        SERVICE_NAME: api-gateway-service
    env_file: api-gateway-service/.env
    ports:
      - "127.0.0.1:8082:8082"
    depends_on:
      - trades-receiver-service
      - redis
    networks:
      - insider-trades

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "127.0.0.1:5432:5432"
      - "127.0.0.1:6432:6432"
    networks:
      - insider-trades

  redis:
    container_name: redis
    image: redis:7.0.0-alpine
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}
    #    volumes:
    #      - redis:/data
    networks:
      - insider-trades


  migrate:
    profiles: [ "pkg" ]
    image: migrate/migrate
    # entrypoint: "migrate -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=disable -path /migrations"
    entrypoint: "migrate -database ${POSTGRES_URL} -path /trades-receiver-service/migrations"
    command: ""
    volumes:
      - ./migrations:/migrations
    networks:
      - insider-trades

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./api:/usr/share/nginx/html/doc
    environment:
      API_URL: api/swagger.yaml
      BASE_URL: "/swagger"
      PORT: "80"
    networks:
      - insider-trades

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.15-management-alpine
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error}]"
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    networks:
      - insider-trades

volumes:
  data:

networks:
  insider-trades:
    name: insider-trades
    driver: bridge
