app:
  name: 'insider-trades-receiver'
  version: '1.0.0'
http_server:
  allow_origin: '*'
  port: ':8080'
grpc_server:
  port: ':50051'
logger:
  level: 'debug'
  format: 'console'
  filepath: './trades-receiver-service.log'
rabbitmq:
  exchange: 'trades'
  durable: true
  queueName: 'telegram_channel_queue'
  routingKey: ''
  consumerName: 'telegram_notification'
