version: "3.8"

services:
  trades-receiver:
    container_name: trades-receiver
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      POSTGRES_URL: postgres://trades_receiver:defaultpass@localhost:5432/trades
    ports:
      - "8080:8080"
    depends_on:
      - "db"

  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: "trades_receiver"
      POSTGRES_PASSWORD: "defaultpass"
      POSTGRES_DB: 'postgres'