version: "3.8"

services:
  trades-receiver:
    container_name: trades-receiver
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - insider-trades

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - insider-trades

  migrate:
    profiles: ["pkg"]
    image: migrate/migrate
    entrypoint: "migrate -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=disable -path /migrations"
    command: ""
    links:
      - postgres
    volumes:
      - ./migrations:/migrations
    networks:
      - insider-trades

volumes:
  data:

networks:
  insider-trades:
    name: insider-trades
    driver: bridge
