version: "3.8"

services:
  trades-receiver:
    container_name: trades-receiver
    image: trades-receiver
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - insider-trades

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - insider-trades

  migrate:
    profiles: [ "pkg" ]
    image: migrate/migrate
    entrypoint: "migrate -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=disable -path /migrations"
    command: ""
    volumes:
      - ./migrations:/migrations
    networks:
      - insider-trades

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "80:80"
    volumes:
      - ./docs:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/swagger.yaml
      BASE_URL: "/swagger"
      PORT: "80"
    networks:
      - insider-trades

volumes:
  data:

networks:
  insider-trades:
    name: insider-trades
    driver: bridge
