app:
  name: 'telegram-notification-service'
  version: '1.0.0'
server:
  port: ':8081'
logger:
  level: 'debug'
  format: 'console'
  filepath: './telegram-notification-service.log'
rabbitmq:
  exchange: 'trades'
  durable: true
  queueName: 'telegram_channel_queue'
  routingKey: ''
  consumerName: 'telegram_notification'
