// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	entity "github.com/alexbobkovv/insider-trades/trades-receiver-service/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockInsiderTrade is a mock of InsiderTrade interface.
type MockInsiderTrade struct {
	ctrl     *gomock.Controller
	recorder *MockInsiderTradeMockRecorder
}

// MockInsiderTradeMockRecorder is the mock recorder for MockInsiderTrade.
type MockInsiderTradeMockRecorder struct {
	mock *MockInsiderTrade
}

// NewMockInsiderTrade creates a new mock instance.
func NewMockInsiderTrade(ctrl *gomock.Controller) *MockInsiderTrade {
	mock := &MockInsiderTrade{ctrl: ctrl}
	mock.recorder = &MockInsiderTradeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInsiderTrade) EXPECT() *MockInsiderTradeMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockInsiderTrade) GetAll(ctx context.Context, cursor string, limit int) ([]*entity.Transaction, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, cursor, limit)
	ret0, _ := ret[0].([]*entity.Transaction)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockInsiderTradeMockRecorder) GetAll(ctx, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockInsiderTrade)(nil).GetAll), ctx, cursor, limit)
}

// Receive mocks base method.
func (m *MockInsiderTrade) Receive(ctx context.Context, trade *entity.Trade) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive", ctx, trade)
	ret0, _ := ret[0].(error)
	return ret0
}

// Receive indicates an expected call of Receive.
func (mr *MockInsiderTradeMockRecorder) Receive(ctx, trade interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockInsiderTrade)(nil).Receive), ctx, trade)
}

// MockInsiderTradeRepo is a mock of InsiderTradeRepo interface.
type MockInsiderTradeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInsiderTradeRepoMockRecorder
}

// MockInsiderTradeRepoMockRecorder is the mock recorder for MockInsiderTradeRepo.
type MockInsiderTradeRepoMockRecorder struct {
	mock *MockInsiderTradeRepo
}

// NewMockInsiderTradeRepo creates a new mock instance.
func NewMockInsiderTradeRepo(ctrl *gomock.Controller) *MockInsiderTradeRepo {
	mock := &MockInsiderTradeRepo{ctrl: ctrl}
	mock.recorder = &MockInsiderTradeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInsiderTradeRepo) EXPECT() *MockInsiderTradeRepoMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockInsiderTradeRepo) GetAll(ctx context.Context, cursor string, limit int) ([]*entity.Transaction, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, cursor, limit)
	ret0, _ := ret[0].([]*entity.Transaction)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockInsiderTradeRepoMockRecorder) GetAll(ctx, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockInsiderTradeRepo)(nil).GetAll), ctx, cursor, limit)
}

// StoreTrade mocks base method.
func (m *MockInsiderTradeRepo) StoreTrade(ctx context.Context, trade *entity.Trade) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTrade", ctx, trade)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreTrade indicates an expected call of StoreTrade.
func (mr *MockInsiderTradeRepoMockRecorder) StoreTrade(ctx, trade interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTrade", reflect.TypeOf((*MockInsiderTradeRepo)(nil).StoreTrade), ctx, trade)
}

// MockInsiderTradePublisher is a mock of InsiderTradePublisher interface.
type MockInsiderTradePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockInsiderTradePublisherMockRecorder
}

// MockInsiderTradePublisherMockRecorder is the mock recorder for MockInsiderTradePublisher.
type MockInsiderTradePublisherMockRecorder struct {
	mock *MockInsiderTradePublisher
}

// NewMockInsiderTradePublisher creates a new mock instance.
func NewMockInsiderTradePublisher(ctrl *gomock.Controller) *MockInsiderTradePublisher {
	mock := &MockInsiderTradePublisher{ctrl: ctrl}
	mock.recorder = &MockInsiderTradePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInsiderTradePublisher) EXPECT() *MockInsiderTradePublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockInsiderTradePublisher) Publish(ctx context.Context, trade *entity.Trade) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, trade)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockInsiderTradePublisherMockRecorder) Publish(ctx, trade interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockInsiderTradePublisher)(nil).Publish), ctx, trade)
}
