version: '3.8'
services:
  telegram-notification-service:
    container_name: telegram-notification-service
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - insider-trades
networks:
  insider-trades:
    external: 
      name: insider-trades
