name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: unit-tests
        run: "go test \
            -v \
            -race \
            -covermode atomic \
            -coverprofile=coverage.txt \
            ./internal/..."
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)