name: deploy

on:
  #  workflow_run:
  #    workflows: [ CI ]
  #    branches: [ main ]
  #    types:
  #      - completed
  push:

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push receiver-service
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: {context}/Dockerfile.prod
          build-args: SERVICE_NAME=trades-receiver-service
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/insider-trades:receiver

      - name: Build and push telegram-notification-service
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: {context}/Dockerfile.prod
          build-args: SERVICE_NAME=telegram-notification-service
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/insider-trades:telegram-notification
